#!/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin

exec 2> >(sed 's/^/:: /')
set -v

. /etc/rc.conf

echo 'Waiting for services to stop...'
sv -w196 force-stop /var/service/*
sv exit /var/service/*

stty onlcr
echo Shutdown...

runlevel=$(readlink -f /etc/runit/runsvdir/current)
runlevel=${runlevel#/run/service.}
[[ $runlevel = /run/service ]] && ref="DAEMONS[@]" || ref="DAEMONS_${runlevel}[@]"

for daemon in "${!ref}"; do
  case ${daemon:0:1} in
    !) ;;
    *) [[ -d /etc/sv/$daemon ]] || /etc/rc.d/$daemon stop;;
  esac
done

[ -x /etc/rc.local.shutdown ] && /etc/rc.local.shutdown

dd if=/dev/urandom of=/var/lib/random-seed count=1 bs=512 &>/dev/null

halt -w  # for utmp

[[ $USELVM = yes ]] && vgchange --monitor n

udevadm control --exit

killall5 -15
i=10; while killall5 -18 && (( i-- )) ; do echo -n .; sleep 0.5; done; echo
killall5 -9

umount /tmp
swapoff -a
umount -r -a -t nosysfs,noproc,nodevtmpfs,notmpfs

[[ $USELVM = yes ]] && vgchange --sysinit -a n
#cryptsetup luksClose data
#[[ $USELVM = yes ]] && vgchange --sysinit -a n

mount -o remount,ro /
sleep 1
sync
