#!/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin

exec 2> >(sed 's/^/:: /')
set -v

. /etc/rc.conf

echo 'Waiting for services to stop...'
sv -w196 force-stop /var/service/*
sv exit /var/service/*

stty onlcr
echo Shutdown...

runlevel=$(readlink -f /etc/runit/runsvdir/current)
runlevel=${runlevel#/run/service.}
[[ $runlevel = /run/service ]] && ref="DAEMONS[@]" || ref="DAEMONS_${runlevel}[@]"

[ -x /etc/rc.local.shutdown ] && /etc/rc.local.shutdown

dd if=/dev/urandom of=/var/lib/random-seed count=1 bs=512 &>/dev/null

hwclock --systohc ${HARDWARECLOCK:+--$(echo $HARDWARECLOCK |tr A-Z a-z)}

halt -w  # for utmp

[[ $USELVM = yes ]] && vgchange --monitor n

udevadm control --exit

killall5 -15
i=10; while killall5 -18 && (( i-- )) ; do echo -n .; sleep 0.5; done; echo
killall5 -9

umount /tmp
swapoff -a
umount -r -a -t nosysfs,noproc,nodevtmpfs,notmpfs

[[ $USELVM = yes ]] && vgchange --sysinit -a n
awk '/^#/ || /^$/ { next }
     NF>2 { print "ignite unsupported crypttab: " $0 >"/dev/stderr"; next }
     { system("cryptsetup luksClose " $1) }' </etc/crypttab
[[ $USELVM = yes ]] && vgchange --sysinit -a n

mount -o remount,ro /
sleep 1
sync
